#!/bin/sh

MACADDR=$(ip link | grep wlan0: -A 1 | tail -n 1 | awk '{gsub(/:/,""); print toupper($2)}')
WIFISSID=OpenWrt-$MACADDR

uci set wireless.radio0.disabled=0
uci set wireless.default_radio0.ssid=$WIFISSID
uci set wireless.radio0.country='CN'
uci set wireless.radio0.channel='auto'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
echo CST-8 > /etc/TZ
uci commit
wifi

sleep 3
rm /etc/rc.local.d/00firstboot
